export const AuthConstant = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILUER: "LOGIN_FAILUER",
    LOGIN_GOOGLE_SUCCESS: "LOGIN_GOOGLE_SUCCESS",
    LOGIN_GOOGLE_FAILUER: "LOGIN_GOOGLE_FAILUER",
}
