export const AuthConstant = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILUER: "LOGIN_FAILUER",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILUER: "REGISTER_FAILUER",
    LOGIN_GOOGLE_SUCCESS: "LOGIN_GOOGLE_SUCCESS",
    LOGIN_GOOGLE_FAILUER: "LOGIN_GOOGLE_FAILUER",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
}
