export const MdmVslCntrConstant = {
  GET_MDM_VSL_CNTR_LIST_SUCCESS: "GET_MDM_VSL_CNTR_LIST_SUCCESS",
  GET_MDM_VSL_CNTR_LIST_FAILUER: "GET_MDM_VSL_CNTR_LIST_FAILUER",
  GET_MDM_VSL_CNTR_ITEM_SUCCESS: "GET_MDM_VSL_CNTR_ITEM_SUCCESS",
  GET_MDM_VSL_CNTR_ITEM_FAILUER: "GET_MDM_VSL_CNTR_ITEM_FAILUER",
  ADD_MDM_VSL_CNTR_ITEM_SUCCESS: "ADD_MDM_VSL_CNTR_ITEM_SUCCESS",
  ADD_MDM_VSL_CNTR_ITEM_FAILUER: "ADD_MDM_VSL_CNTR_ITEM_FAILUER",
  EDIT_MDM_VSL_CNTR_ITEM_SUCCESS: "EDIT_MDM_VSL_CNTR_ITEM_SUCCESS",
  EDIT_MDM_VSL_CNTR_ITEM_FAILURE: "EDIT_MDM_VSL_CNTR_ITEM_FAILURE",
  REMOVE_MDM_VSL_CNTR_ITEM_SUCCESS: "REMOVE_MDM_VSL_CNTR_ITEM_SUCCESS",
  REMOVE_MDM_VSL_CNTR_ITEM_FAILURE: "REMOVE_MDM_VSL_CNTR_ITEM_FAILURE",

  SET_CALLBACK_NEXT_STEP_ACTION: "SET_CALLBACK_NEXT_STEP_ACTION",
  SET_NEXT_STEP_DATA: 'SET_NEXT_STEP_DATA',
  SET_PREVIOUS_STEP_DATA: 'SET_PREVIOUS_STEP_DATA',
};
