export const MenuConstant = {
    GET_MENU_LIST_SUCCESS: "GET_MENU_LIST_SUCCESS",
    GET_MENU_LIST_FAILUER: "GET_MENU_LIST_FAILUER",
    GET_MENU_ITEM_SUCCESS: "GET_MENU_ITEM_SUCCESS",
    GET_MENU_ITEM_FAILUER: "GET_MENU_ITEM_FAILUER",
    ADD_MENU_ITEM_SUCCESS: "ADD_MENU_ITEM_SUCCESS",
    ADD_MENU_ITEM_FAILUER: "ADD_MENU_ITEM_FAILUER",
    EDIT_MENU_ITEM_SUCCESS: "EDIT_MENU_ITEM_SUCCESS",
    EDIT_MENU_ITEM_FAILURE: "EDIT_MENU_ITEM_FAILURE",
    REMOVE_MENU_ITEM_SUCCESS: "REMOVE_MENU_ITEM_SUCCESS",
    REMOVE_MENU_ITEM_FAILURE: "REMOVE_MENU_ITEM_FAILURE",
}
