export const PermissionGroupConstant = {
    GET_PERMISSION_GROUP_LIST_SUCCESS: "GET_PERMISSION_GROUP_LIST_SUCCESS",
    GET_PERMISSION_GROUP_LIST_FAILUER: "GET_PERMISSION_GROUP_LIST_FAILUER",
    GET_PERMISSION_GROUP_ITEM_SUCCESS: "GET_PERMISSION_GROUP_ITEM_SUCCESS",
    GET_PERMISSION_GROUP_ITEM_FAILUER: "GET_PERMISSION_GROUP_ITEM_FAILUER",
    ADD_PERMISSION_GROUP_ITEM_SUCCESS: "ADD_PERMISSION_GROUP_ITEM_SUCCESS",
    ADD_PERMISSION_GROUP_ITEM_FAILUER: "ADD_PERMISSION_GROUP_ITEM_FAILUER",
    EDIT_PERMISSION_GROUP_ITEM_SUCCESS: "EDIT_PERMISSION_GROUP_ITEM_SUCCESS",
    EDIT_PERMISSION_GROUP_ITEM_FAILURE: "EDIT_PERMISSION_GROUP_ITEM_FAILURE",
    REMOVE_PERMISSION_GROUP_ITEM_SUCCESS: "REMOVE_PERMISSION_GROUP_ITEM_SUCCESS",
    REMOVE_PERMISSION_GROUP_ITEM_FAILURE: "REMOVE_PERMISSION_GROUP_ITEM_FAILURE",
}
