export const PermissionConstant = {
    GET_PERMISSION_LIST_SUCCESS: "GET_PERMISSION_LIST_SUCCESS",
    GET_PERMISSION_LIST_FAILUER: "GET_PERMISSION_LIST_FAILUER",
    GET_PERMISSION_ITEM_SUCCESS: "GET_PERMISSION_ITEM_SUCCESS",
    GET_PERMISSION_ITEM_FAILUER: "GET_PERMISSION_ITEM_FAILUER",
    ADD_PERMISSION_ITEM_SUCCESS: "ADD_PERMISSION_ITEM_SUCCESS",
    ADD_PERMISSION_ITEM_FAILUER: "ADD_PERMISSION_ITEM_FAILUER",
    EDIT_PERMISSION_ITEM_SUCCESS: "EDIT_PERMISSION_ITEM_SUCCESS",
    EDIT_PERMISSION_ITEM_FAILURE: "EDIT_PERMISSION_ITEM_FAILURE",
    REMOVE_PERMISSION_ITEM_SUCCESS: "REMOVE_PERMISSION_ITEM_SUCCESS",
    REMOVE_PERMISSION_ITEM_FAILURE: "REMOVE_PERMISSION_ITEM_FAILURE",
}
