export const RoleConstant = {
    GET_ROLE_LIST_SUCCESS: "GET_ROLE_LIST_SUCCESS",
    GET_ROLE_LIST_FAILUER: "GET_ROLE_LIST_FAILUER",
    GET_ROLE_ITEM_SUCCESS: "GET_ROLE_ITEM_SUCCESS",
    GET_ROLE_ITEM_FAILUER: "GET_ROLE_ITEM_FAILUER",
    ADD_ROLE_ITEM_SUCCESS: "ADD_ROLE_ITEM_SUCCESS",
    ADD_ROLE_ITEM_FAILUER: "ADD_ROLE_ITEM_FAILUER",
    EDIT_ROLE_ITEM_SUCCESS: "EDIT_ROLE_ITEM_SUCCESS",
    EDIT_ROLE_ITEM_FAILURE: "EDIT_ROLE_ITEM_FAILURE",
    REMOVE_ROLE_ITEM_SUCCESS: "REMOVE_ROLE_ITEM_SUCCESS",
    REMOVE_ROLE_ITEM_FAILURE: "REMOVE_ROLE_ITEM_FAILURE",
}
