export const RolePermissionConstant = {
    GET_ROLE_PERMISSION_LIST_SUCCESS: "GET_ROLE_PERMISSION_LIST_SUCCESS",
    GET_ROLE_PERMISSION_LIST_FAILUER: "GET_ROLE_PERMISSION_LIST_FAILUER",
    GET_ROLE_PERMISSION_ITEM_SUCCESS: "GET_ROLE_PERMISSION_ITEM_SUCCESS",
    GET_ROLE_PERMISSION_ITEM_FAILUER: "GET_ROLE_PERMISSION_ITEM_FAILUER",
    ADD_ROLE_PERMISSION_ITEM_SUCCESS: "ADD_ROLE_PERMISSION_ITEM_SUCCESS",
    ADD_ROLE_PERMISSION_ITEM_FAILUER: "ADD_ROLE_PERMISSION_ITEM_FAILUER",
    EDIT_ROLE_PERMISSION_ITEM_SUCCESS: "EDIT_ROLE_PERMISSION_ITEM_SUCCESS",
    EDIT_ROLE_PERMISSION_ITEM_FAILURE: "EDIT_ROLE_PERMISSION_ITEM_FAILURE",
    REMOVE_ROLE_PERMISSION_ITEM_SUCCESS: "REMOVE_ROLE_PERMISSION_ITEM_SUCCESS",
    REMOVE_ROLE_PERMISSION_ITEM_FAILURE: "REMOVE_ROLE_PERMISSION_ITEM_FAILURE",
}
