export const UserRoleConstant = {
    GET_USER_ROLE_LIST_SUCCESS: "GET_USER_ROLE_LIST_SUCCESS",
    GET_USER_ROLE_LIST_FAILUER: "GET_USER_ROLE_LIST_FAILUER",
    GET_USER_ROLE_ITEM_SUCCESS: "GET_USER_ROLE_ITEM_SUCCESS",
    GET_USER_ROLE_ITEM_FAILUER: "GET_USER_ROLE_ITEM_FAILUER",
    ADD_USER_ROLE_ITEM_SUCCESS: "ADD_USER_ROLE_ITEM_SUCCESS",
    ADD_USER_ROLE_ITEM_FAILUER: "ADD_USER_ROLE_ITEM_FAILUER",
    EDIT_USER_ROLE_ITEM_SUCCESS: "EDIT_USER_ROLE_ITEM_SUCCESS",
    EDIT_USER_ROLE_ITEM_FAILURE: "EDIT_USER_ROLE_ITEM_FAILURE",
    REMOVE_USER_ROLE_ITEM_SUCCESS: "REMOVE_USER_ROLE_ITEM_SUCCESS",
    REMOVE_USER_ROLE_ITEM_FAILURE: "REMOVE_USER_ROLE_ITEM_FAILURE",
}
